CREATE TABLE IF NOT EXISTS Musician (
	id SERIAL PRIMARY KEY,
	Name VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Genre (
	id SERIAL PRIMARY KEY,
	GenreName VARCHAR (30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Album (
	id SERIAL PRIMARY KEY,
	Album_Title VARCHAR (40) NOT NULL,
	Album_Year INTEGER
);

CREATE TABLE IF NOT EXISTS Track (
	id SERIAL PRIMARY KEY REFERENCES Album(id),
	Track_Title VARCHAR (40),
	Track_Length INTERVAL
);

CREATE TABLE IF NOT EXISTS Collection (
	id SERIAL PRIMARY KEY,
	Collection_Title VARCHAR (40) NOT NUll,
	Collection_Year INTEGER
);

CREATE TABLE IF NOT EXISTS MusicianGenre (
	MusicianID INTEGER REFERENCES Musician(id),
	GenreID INTEGER REFERENCES Genre(id),
	CONSTRAINT pk PRIMARY KEY (MusicianID,
GenreID)
);

CREATE TABLE IF NOT EXISTS AlbumMusician (
	MusicianID INTEGER REFERENCES Musician(id),
	AlbumID INTEGER REFERENCES Album(id),
	CONSTRAINT pk1 PRIMARY KEY (MusicianID,
AlbumID)
);

CREATE TABLE IF NOT EXISTS CollectionTrack (
	CollectionID INTEGER REFERENCES Collection(id),
	TrackID INTEGER REFERENCES Track(id),
	CONSTRAINT pk2 PRIMARY KEY (CollectionID,
TrackID)
)

